### ISSUE TITLE
Exception while parsing config file

### ISSUE THREAD

**Issue by muthukdi** [sivasamyk/graylog-plugin-input-jmx#2]
Hi,

I am trying to use this with Graylog 2.0.1 but I'm getting the following error when I try to launch the input for JVM monitoring:

2016-05-19 08:54:10,971 ERROR: org.graylog.inputs.jmx.JMXTransport - Exception while parsing config file
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3716) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2794) ~[graylog.jar:?]
    at org.graylog.inputs.jmx.JMXTransport.launch(JMXTransport.java:127) [graylog-plugin-input-jmx-1.0.0-SNAPSHOT.jar:?]
    at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:153) [graylog.jar:?]
    at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84) [graylog.jar:?]
    at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2016-05-19 08:54:10,975 ERROR: org.graylog2.shared.inputs.InputLauncher - The [org.graylog.inputs.jmx.JMXInput] input with ID <573db772df62b961586eb8a3> misfired. Reason: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1].
org.graylog2.plugin.inputs.MisfireException: org.graylog2.plugin.inputs.MisfireException: Exception while parsing config file JVM
    at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:156) ~[graylog.jar:?]
    at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84) [graylog.jar:?]
    at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.graylog2.plugin.inputs.MisfireException: Exception while parsing config file JVM
    at org.graylog.inputs.jmx.JMXTransport.launch(JMXTransport.java:133) ~[?:?]
    at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:153) ~[graylog.jar:?]
    ... 7 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3716) ~[graylog.jar:?]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2794) ~[graylog.jar:?]
    at org.graylog.inputs.jmx.JMXTransport.launch(JMXTransport.java:127) ~[?:?]
    at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:153) ~[graylog.jar:?]
    ... 7 more
2016-05-19 08:54:10,977 ERROR: com.google.common.eventbus.EventBus.graylog-eventbus - Exception thrown by subscriber method inputStateChanged(org.graylog2.plugin.events.inputs.IOStateChangedEvent) on subscriber org.graylog2.inputs.InputStateListener@32d46229 when dispatching event: IOStateChangedEvent{oldState=STARTING, newState=FAILED, changedState=InputState{stoppable=JMXInput{title=FIDS JMX Input, type=org.graylog.inputs.jmx.JMXInput, nodeId=85f479de-dbd4-45c1-8434-6241186c0a42}, state=FAILED, startedAt=2016-05-19T12:54:10.951Z, detailedMessage='null'}}
java.lang.NullPointerException
    at org.graylog2.system.activities.SystemMessageImpl.<init>(SystemMessageImpl.java:44) ~[graylog.jar:?]
    at org.graylog2.system.activities.SystemMessageServiceImpl.create(SystemMessageServiceImpl.java:60) ~[graylog.jar:?]
    at org.graylog2.system.activities.SystemMessageActivityWriter.write(SystemMessageActivityWriter.java:55) ~[graylog.jar:?]
    at org.graylog2.inputs.InputStateListener.inputStateChanged(InputStateListener.java:57) ~[graylog.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:95) ~[graylog.jar:?]
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:154) ~[graylog.jar:?]
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:80) [graylog.jar:?]
    at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

I have configured the input as follows:

"title": "FIDS JMX Input",
      "global": false,
      "name": "JMX",
      "content_pack": null,
      "created_at": "2016-05-19T12:54:10.685Z",
      "type": "org.graylog.inputs.jmx.JMXInput",
      "creator_user_id": "admin",
      "attributes": {
        "configLabel": "FIDS HTTP monitor",
        "configPassword": "",
        "override_source": null,
        "configHosts": "vtor-lx-tomcat-u01",
        "configType": "JVM",
        "configCustomFilePath": "",
        "configInterval": 1,
        "configPort": 12345,
        "configUsername": "",
        "configIntervalUnit": "SECONDS"
      },
      "static_fields": {},
      "node": "85f479de-dbd4-45c1-8434-6241186c0a42",
      "id": "573db772df62b961586eb8a3"

This worked when I tried it with Graylog 1.3.4.

**Comment by sivasamyk** [comment]
Looks like some API broken in Graylog 2.0.0. I have raised an issue on graylog-server to track this.

[https://github.com/Graylog2/graylog2-server/issues/2295](https://github.com/Graylog2/graylog2-server/issues/2295)

**Comment by sivasamyk** [comment]
This was due to wrong default value in the plugin. Fixed the same. download the latest release (1.0.1).
