### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by SwagMuffinMcYoloPants** [sivasamyk/graylog-plugin-input-jmx#5]
Is it possible to use SSL with this input plugin?  The example only does barebones without SSL.

**Comment by sivasamyk** [comment]
Currently the plugin does not support SSL. Will update soon.

**Comment by sivasamyk** [comment]
Added SSL support. Get the latest release from [here](https://github.com/sivasamyk/graylog-plugin-input-jmx/releases/download/v1.0.2/graylog-plugin-input-jmx-1.0.2-SNAPSHOT.jar) and let me know if it works.
Updated readme with steps to enable SSL.

**Comment by SwagMuffinMcYoloPants** [comment]
HI.  I tried using the new plugin you provided in your last post.  I couldn't get it to work.  I used the flags that you provided.  I used VisualVM to try to connect to from my local machine and it initially didn't work.  After adding the VisualVM-Security plugin and adding the trust store, it connected to the remote server.

**Comment by sivasamyk** [comment]
Please let me know if there are any exceptions in graylog server log. Also send me the command line params you are passing to the Java application, to enable remote JMX monitoring.

**Comment by SwagMuffinMcYoloPants** [comment]
I checked the server.log file mentioned in the log4j2.xml file in /etc/graylog/server.  Nothing out of the ordinary shows up.

```
2016-09-12T14:51:26.507-04:00 INFO  [InputStateListener] Input [JMX/57d1c31b57aae11b0107e99d] is now RUNNING
2016-09-12T15:09:32.617-04:00 INFO  [InputStateListener] Input [JMX/57d1c31b57aae11b0107e99d] is now STOPPING
2016-09-12T15:09:32.617-04:00 INFO  [InputStateListener] Input [JMX/57d1c31b57aae11b0107e99d] is now STOPPED
2016-09-12T15:09:32.618-04:00 INFO  [InputStateListener] Input [JMX/57d1c31b57aae11b0107e99d] is now TERMINATED
2016-09-12T15:09:32.620-04:00 INFO  [InputStateListener] Input [JMX/57d1c31b57aae11b0107e99d] is now STARTING
2016-09-12T15:09:32.621-04:00 INFO  [JMXTransport] JMX Input Plugin started ...
2016-09-12T15:09:32.622-04:00 INFO  [InputStateListener] Input [JMX/57d1c31b57aae11b0107e99d] is now RUNNING
```

I have the following added to my setenv.sh in my Tomcat.

```
export CATALINA_OPTS="$CATALINA_OPTS -Djavax.net.ssl.trustStore=$CATALINA_BASE/certs/keystore.jks -Djavax.net.ssl.trustStorePassword=PASSWORD"
export CATALINA_OPTS="$CATALINA_OPTS -Djavax.net.ssl.keyStore=$CATALINA_BASE/certs/keystore.jks -Djavax.net.ssl.keyStorePassword=PASSWORD"
export CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=true -Djava.rmi.server.hostname=10.0.0.2 -Dcom.sun.management.jmxremote.ssl.need.client.auth=false"
export CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.registry.ssl=true"
```

**Comment by sivasamyk** [comment]
The plugin polls the Java app periodically and tries to establish connection during polling. Can you let the plugin run for 3-4 mins ( based on your configured poll interval) and check if there are any exceptions in log file? This is required because the plugin will start connecting to the Java app with delay after the starting.  Your env vars looks good.

**Comment by SwagMuffinMcYoloPants** [comment]
I set the polling interval to 5 seconds because I got impatient.  Nothing still gets printed in the log file.

**Comment by sivasamyk** [comment]
@SwagMuffinMcYoloPants I assume you removed old plugin jar (1.0.1) from plugins dir of graylog ( please check if there are multiple jmx plugins jars. The new jar version is 1.0.2).  Can you downloading plugin jar present in attached zip file ( I have added more logger statements) and let know the contents of logs file?

[graylog-plugin-input-jmx-1.0.2-SNAPSHOT.jar.zip](https://github.com/sivasamyk/graylog-plugin-input-jmx/files/470167/graylog-plugin-input-jmx-1.0.2-SNAPSHOT.jar.zip)

**Comment by SwagMuffinMcYoloPants** [comment]
The logs printed out an error with the new jar you gave.  It printed the following:

```
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:1.8.0_101]
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:1.8.0_101]
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[?:1.8.0_101]
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[?:1.8.0_101]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[?:1.8.0_101]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_101]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_101]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_101]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_101]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491) ~[?:1.8.0_101]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_101]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_101]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[?:1.8.0_101]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[?:1.8.0_101]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_101]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747) ~[?:1.8.0_101]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[?:1.8.0_101]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_101]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_101]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[?:1.8.0_101]
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:229) ~[?:1.8.0_101]
        ... 20 more
```

I ended up adding my specific certificate into the Java cacerts trust store and everything worked.  The problem was on my side.  Thank you for your time.
